version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CONFIG_PATH=/app/configs/${CONFIG_FILE:-postgres.yaml}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  migrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CONFIG_PATH=/app/configs/${CONFIG_FILE:-postgres.yaml}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ["sh", "-c", "/app/wait-for-postgres.sh postgres 5432 && ./migrator"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: comments
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d comments"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: