FROM golang:1.24.3-alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux

WORKDIR /api

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -ldflags="-w -s" -o comments-system ./cmd/comments-system/main.go

FROM alpine:latest

RUN apk add --no-cache \
    postgresql15-client \
    tzdata

WORKDIR /api
COPY --from=builder /api/config ./config
COPY --from=builder /api/comments-system .
COPY --from=builder /api/.env . 

CMD ["db", "5432", "./comments-system"]