env: local
migrations: "./migrations"

server:
  port: "8080"

postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "comments"
  sslmode: "disable"

storage: "postgres" # или "inmemory"