// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "comments-system/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PostStorage is an autogenerated mock type for the PostStorage type
type PostStorage struct {
	mock.Mock
}

// CreatePost provides a mock function with given fields: ctx, post
func (_m *PostStorage) CreatePost(ctx context.Context, post models.Post) (models.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) (models.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) models.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPost provides a mock function with given fields: ctx, id
func (_m *PostStorage) GetPost(ctx context.Context, id string) (models.Post, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Post, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Post); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosts provides a mock function with given fields: ctx, limit, offset
func (_m *PostStorage) GetPosts(ctx context.Context, limit int, offset int) ([]models.Post, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Post, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Post); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePost provides a mock function with given fields: ctx, post
func (_m *PostStorage) UpdatePost(ctx context.Context, post models.Post) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Post) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostStorage creates a new instance of PostStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostStorage {
	mock := &PostStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
